twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null

    globals:
            evento: Dias de puertas abiertas del posgrado en Matemáticas de Morelia
